/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author migue
 */
public class TelaPrincipal extends javax.swing.JFrame {

    float celsius,kelvin,fahrenheit;
   
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputc = new javax.swing.JTextField();
        title = new javax.swing.JLabel();
        labelc = new javax.swing.JLabel();
        labelk = new javax.swing.JLabel();
        btnc = new javax.swing.JButton();
        btnclear = new javax.swing.JToggleButton();
        labelf = new javax.swing.JLabel();
        outk = new javax.swing.JLabel();
        outf = new javax.swing.JLabel();
        label_msg = new javax.swing.JLabel();

        setResizable(false);

        inputc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputcActionPerformed(evt);
            }
        });

        title.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        title.setText("Conversor de Temperaturas");

        labelc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelc.setText("Celsius");

        labelk.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelk.setText("Kelvin:");

        btnc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnc.setText("Converter");
        btnc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncActionPerformed(evt);
            }
        });

        btnclear.setText("Limpar");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        labelf.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelf.setText("Fahrenheit:");

        outk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        outk.setText("Esperando Informações");
        outk.setAlignmentX(5.0F);
        outk.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        outf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        outf.setText("Esperando Informações");
        outf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        label_msg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_msg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(inputc, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(btnc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(labelc))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelf)
                            .addComponent(outf, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(outk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(label_msg, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(title))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelk)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(labelc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(outk, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(outf, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                    .addComponent(label_msg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );

        getAccessibleContext().setAccessibleName("Conversor de Temperatura");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputcActionPerformed
        // para digitar temperatura em celcius
    }//GEN-LAST:event_inputcActionPerformed

    private void btncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncActionPerformed
      //botao de converter
      
      
      celsius =  Float.parseFloat(inputc.getText());
      fahrenheit = ((celsius * 9)/5)+32;
      kelvin = celsius + 273;
      
      inputc.setText("");
        outk.setText("");
        outf.setText("");
      outf.setText(""+fahrenheit);
      outk.setText(""+kelvin);
     
      if(celsius<=0){
          label_msg.setText("Temperatura Muito Baixa!");
      }else if(celsius<=10){
          label_msg.setText("Temperatura Baixa!");
      }
      else if(celsius<=30){
          label_msg.setText("Temperatura Agradavel!");
      }else if(celsius<=45){
          label_msg.setText("Temperatura Quente!");
      }
      else{
          label_msg.setText("Temperatura Muito Quente!");
      }
      
    
    }//GEN-LAST:event_btncActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        //botao limpar
        celsius = 0;
        fahrenheit = 0;
        kelvin = 0;
        
        label_msg.setText("");
        inputc.setText("");
        outk.setText("Esperando Informações");
        outf.setText("Esperando Informações");
               
    }//GEN-LAST:event_btnclearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnc;
    private javax.swing.JToggleButton btnclear;
    private javax.swing.JTextField inputc;
    private javax.swing.JLabel label_msg;
    private javax.swing.JLabel labelc;
    private javax.swing.JLabel labelf;
    private javax.swing.JLabel labelk;
    private javax.swing.JLabel outf;
    private javax.swing.JLabel outk;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
